services:
  whatsupdocker:
    image: getwud/wud:8.1.0
    user: 568:999
    container_name: wud
    volumes:
      - /mnt/Main/Docker/Whats-up-Docker/Store:/store
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    environment:
      - WUD_PUBLIC_URL=https://wud.tom-wiegand.de
      - WUD_AUTH_OIDC_pocket-id_CLIENTID=[REDACTED]
      - WUD_AUTH_OIDC_pocket-id_CLIENTSECRET=[REDACTED]
      - WUD_AUTH_OIDC_pocket-id_DISCOVERY=[REDACTED]
      - WUD_AUTH_OIDC_pocket-id_REDIRECT=true
      - WUD_AUTH_OIDC_pocket-id_TIMEOUT=5000
      - TZ=Europe/Berlin
      - WUD_TRIGGER_APPRISE_LOCAL_URL=http://10.0.0.45:8000
      - WUD_TRIGGER_APPRISE_LOCAL_URLS=apprise://10.0.0.45:8000/admin/?tags=all
    restart: unless-stopped
    networks:
      - pangolin
networks:
  pangolin:
    name: pangolin
    external: true