services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    env_file: .env
    privileged: true
    ports:
      - '3001:3001'
    volumes:
      - /mnt/Main/Docker/dashdot:/mnt/host:ro