role_assignment:
  driver: oidc
  oidc_role_mapper:
    role_claim: groups
    role_mapping:
      - role_name: admin
        claim_value: Admin
      - role_name: spaceadmin
        claim_value: Familie
      - role_name: guest
        claim_value: Freunde