services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.tom-wiegand.de
      - NEWT_ID=[REDACTED]
      - NEWT_SECRET=[REDACTED]
      - docker-socket=/var/run/docker.sock
    networks:
      - pangolin
networks:
  pangolin:
    name: pangolin
    driver: bridge
